/**
 * evidence-directory-8d.test.mjs
 *
 * Sub-AC 8d: Verify that the structured evidence directory and index manifest
 * are correctly generated by generateEvidenceDirectory().
 *
 * Checks:
 *   1. generateEvidenceDirectory() returns a manifest without throwing
 *   2. artifacts/evidence/ directory exists after generation
 *   3. artifacts/evidence/index.json is valid JSON with all required fields
 *   4. index.json overall_verdict is PASS
 *   5. screenshots sub-directory exists with >= 1 files
 *   6. logs sub-directory exists with >= 1 files
 *   7. reports sub-directory exists with >= 1 files
 *   8. summary totals match actual file counts
 *   9. At least the 4 core screenshots are present in evidence/screenshots/
 *  10. At least one log file is present in evidence/logs/
 *  11. latest-run-summary.json is present in evidence/reports/
 *  12. ac-playwright-results.json is present in evidence/reports/
 */

import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { generateEvidenceDirectory } from '../src/lib/reports/generate-evidence-directory.mjs';

const __dirname  = path.dirname(fileURLToPath(import.meta.url));
const ROOT       = path.resolve(__dirname, '..');
const EVIDENCE   = path.join(ROOT, 'artifacts', 'evidence');
const INDEX_PATH = path.join(EVIDENCE, 'index.json');

// ── 1. Returns manifest without throwing ─────────────────────────────────────

test('generateEvidenceDirectory returns a manifest object without throwing', async () => {
  const manifest = await generateEvidenceDirectory();
  assert.ok(manifest, 'generateEvidenceDirectory must return a value');
  assert.strictEqual(typeof manifest.manifest_version, 'string', 'manifest_version must be a string');
  assert.strictEqual(typeof manifest.generated_at, 'string', 'generated_at must be a string');
  assert.strictEqual(typeof manifest.project, 'string', 'project must be a string');
  assert.strictEqual(manifest.sub_ac, '8d', 'sub_ac must be "8d"');
});

// ── 2. Evidence directory exists ─────────────────────────────────────────────

test('artifacts/evidence/ directory exists after generateEvidenceDirectory', async () => {
  await generateEvidenceDirectory();
  const stat = await fs.stat(EVIDENCE);
  assert.ok(stat.isDirectory(), 'artifacts/evidence/ must be a directory');
});

// ── 3. index.json is valid JSON with required fields ─────────────────────────

test('artifacts/evidence/index.json is valid JSON with all required top-level fields', async () => {
  await generateEvidenceDirectory();
  const raw = await fs.readFile(INDEX_PATH, 'utf8');
  const manifest = JSON.parse(raw);
  const requiredFields = [
    'manifest_version', 'generated_at', 'project', 'sub_ac',
    'description', 'directory_layout',
    'screenshots', 'logs', 'reports',
    'summary', 'overall_verdict',
  ];
  for (const field of requiredFields) {
    assert.ok(field in manifest, `index.json must have field: ${field}`);
  }
});

// ── 4. overall_verdict is PASS ────────────────────────────────────────────────

test('index.json overall_verdict is PASS', async () => {
  const manifest = await generateEvidenceDirectory();
  assert.strictEqual(
    manifest.overall_verdict,
    'PASS',
    `Expected overall_verdict PASS but got ${manifest.overall_verdict}`
  );
});

// ── 5. screenshots sub-directory ─────────────────────────────────────────────

test('artifacts/evidence/screenshots/ exists and contains PNG files', async () => {
  await generateEvidenceDirectory();
  const screensDir = path.join(EVIDENCE, 'screenshots');
  const stat = await fs.stat(screensDir);
  assert.ok(stat.isDirectory(), 'artifacts/evidence/screenshots/ must be a directory');
  const files = await fs.readdir(screensDir);
  const pngs = files.filter(f => f.endsWith('.png'));
  assert.ok(pngs.length >= 1, `Expected at least 1 PNG in evidence/screenshots/ but got ${pngs.length}`);
});

// ── 6. logs sub-directory ─────────────────────────────────────────────────────

test('artifacts/evidence/logs/ exists and contains at least 1 log file', async () => {
  await generateEvidenceDirectory();
  const logsDir = path.join(EVIDENCE, 'logs');
  const stat = await fs.stat(logsDir);
  assert.ok(stat.isDirectory(), 'artifacts/evidence/logs/ must be a directory');
  const files = await fs.readdir(logsDir);
  assert.ok(files.length >= 1, `Expected at least 1 log file in evidence/logs/ but got ${files.length}`);
});

// ── 7. reports sub-directory ─────────────────────────────────────────────────

test('artifacts/evidence/reports/ exists and contains at least 1 report file', async () => {
  await generateEvidenceDirectory();
  const reportsDir = path.join(EVIDENCE, 'reports');
  const stat = await fs.stat(reportsDir);
  assert.ok(stat.isDirectory(), 'artifacts/evidence/reports/ must be a directory');
  const files = await fs.readdir(reportsDir);
  assert.ok(files.length >= 1, `Expected at least 1 file in evidence/reports/ but got ${files.length}`);
});

// ── 8. Summary totals match actual counts ────────────────────────────────────

test('index.json summary totals match actual file counts', async () => {
  const manifest = await generateEvidenceDirectory();
  assert.strictEqual(
    manifest.summary.screenshots,
    manifest.screenshots.count,
    'summary.screenshots must match screenshots.count'
  );
  assert.strictEqual(
    manifest.summary.logs,
    manifest.logs.count,
    'summary.logs must match logs.count'
  );
  assert.strictEqual(
    manifest.summary.reports,
    manifest.reports.count,
    'summary.reports must match reports.count'
  );
  assert.strictEqual(
    manifest.summary.total_files,
    manifest.summary.screenshots + manifest.summary.logs + manifest.summary.reports,
    'summary.total_files must equal sum of screenshots + logs + reports'
  );
});

// ── 9. Core screenshots present ──────────────────────────────────────────────

test('evidence/screenshots/ contains all 4 core UI state screenshots', async () => {
  await generateEvidenceDirectory();
  const screensDir = path.join(EVIDENCE, 'screenshots');
  const coreScreenshots = [
    '01-initial-load.png',
    '02-simulation-running.png',
    '03-results-populated.png',
    '04-error-state.png',
  ];
  for (const name of coreScreenshots) {
    const filePath = path.join(screensDir, name);
    let stat;
    try {
      stat = await fs.stat(filePath);
    } catch (err) {
      assert.fail(`Core screenshot missing from evidence/screenshots/: ${name}`);
    }
    assert.ok(stat.size > 0, `Core screenshot ${name} has zero size in evidence/screenshots/`);
  }
});

// ── 10. Log file present ─────────────────────────────────────────────────────

test('evidence/logs/ contains at least watchdog.log or a ralph-harness log', async () => {
  await generateEvidenceDirectory();
  const logsDir = path.join(EVIDENCE, 'logs');
  const files = await fs.readdir(logsDir);
  const hasLog = files.some(f => f === 'watchdog.log' || /^ralph-harness-.*\.log$/.test(f));
  assert.ok(hasLog, `Expected watchdog.log or ralph-harness-*.log in evidence/logs/ but found: ${files.join(', ')}`);
});

// ── 11. latest-run-summary.json in reports ───────────────────────────────────

test('evidence/reports/ contains latest-run-summary.json', async () => {
  await generateEvidenceDirectory();
  const filePath = path.join(EVIDENCE, 'reports', 'latest-run-summary.json');
  const stat = await fs.stat(filePath);
  assert.ok(stat.size > 0, 'latest-run-summary.json must be present in evidence/reports/');
});

// ── 12. ac-playwright-results.json in reports ────────────────────────────────

test('evidence/reports/ contains ac-playwright-results.json', async () => {
  await generateEvidenceDirectory();
  const filePath = path.join(EVIDENCE, 'reports', 'ac-playwright-results.json');
  const stat = await fs.stat(filePath);
  assert.ok(stat.size > 0, 'ac-playwright-results.json must be present in evidence/reports/');
});
