/**
 * agent-spawner.mjs
 *
 * Defines the canonical 8-archetype data for the individual-agent simulation pipeline.
 *
 * The ARCHETYPES constant is the single source of truth for archetype definitions
 * in Gen 2 code. Each archetype object matches fixtures/buyer-personas.md exactly.
 *
 * Archetype field contract:
 *   - id / archetype_id  : snake_case identifier string (both fields present for compat)
 *   - label              : Korean display name
 *   - cohort_weight_percent : integer, all 8 must sum to 100
 *   - budget_band        : "low" | "mid" | "high"
 *   - price_sensitivity  : base integer [1–5]
 *   - trust_sensitivity  : base integer [1–5]
 *   - promo_affinity     : base integer [1–5]
 *   - brand_bias         : base integer [1–5]
 *   - pass_threshold     : base float [0–1], probability to skip all purchases
 *   - copy_preference    : Korean phrase describing what copy resonates with this archetype
 *
 * Per-agent trait values are the archetype base ± small Gaussian noise applied at
 * spawn time (see spawnAgentCohort in buyerAgent.mjs). Mock-mode noise uses ±10%
 * multiplicative jitter on the base value, per ontology buyer_agent.sensitivity_profile.
 *
 * Gen 2 entry point: spawnBuyerAgents() generates the full 800-agent cohort using
 * the ARCHETYPES constant defined below, with ±10% multiplicative variation per
 * ontology buyer_agent.sensitivity_profile (sensitivity_variation from agentUtils.mjs).
 */

import { mulberry32 } from './sampler.mjs';
import { buildCohortCounts, ARCHETYPES as _ARCHETYPES_FROM_CONFIG, getArchetypeById as _getArchetypeById, getArchetypeIds as _getArchetypeIds } from './archetypes.mjs';
import { createKoreanNameGenerator, sensitivity_variation } from './agentUtils.mjs';

// ---------------------------------------------------------------------------
// Archetype definitions — canonical source is archetypes.mjs
// Re-exported here for backward compatibility so existing importers of
// agent-spawner.mjs continue to work without changes.
// ---------------------------------------------------------------------------

/**
 * Canonical archetype definitions for all 8 buyer personas.
 * Source of truth: src/lib/simulation/archetypes.mjs
 * Re-exported here for backward compat.
 *
 * @type {ReadonlyArray<object>}
 */
export const ARCHETYPES = _ARCHETYPES_FROM_CONFIG;

/**
 * Look up an archetype by its id.
 * Delegates to archetypes.mjs implementation.
 *
 * @param {string} archetypeId
 * @returns {object} The archetype object
 */
export const getArchetypeById = _getArchetypeById;

/**
 * Returns the list of valid archetype IDs.
 * Delegates to archetypes.mjs implementation.
 *
 * @returns {string[]}
 */
export const getArchetypeIds = _getArchetypeIds;

// ---------------------------------------------------------------------------
// Gen 2 agent spawner — individual-agent simulation entry point
// ---------------------------------------------------------------------------

/**
 * Apply ±10% multiplicative variation to a pass_threshold value.
 * Clamped to [0, 1], rounded to 3 decimal places.
 *
 * @param {number} base - Archetype base pass_threshold (0–1)
 * @param {() => number} rng - RNG function returning a value in [0, 1)
 * @returns {number} Varied pass_threshold in [0, 1]
 */
function varyPassThreshold(base, rng) {
  const factor = rng() * 0.2 - 0.1; // uniform [-0.10, +0.10)
  const varied = base * (1 + factor);
  return Math.min(1, Math.max(0, Math.round(varied * 1000) / 1000));
}

/**
 * Spawn the full 800-agent buyer cohort from the canonical ARCHETYPES.
 *
 * This is the Gen 2 entry point for individual-agent simulation. Each agent:
 *   - Has a unique agent_id in the format "{archetype_id}_{NNNN}" (e.g. "price_sensitive_0001")
 *   - Has a unique Korean name generated by createKoreanNameGenerator (agentUtils.mjs)
 *   - Has independent ±10% multiplicative variation on every sensitivity field
 *     (price_sensitivity, trust_sensitivity, promo_affinity, brand_bias, pass_threshold),
 *     matching ontology buyer_agent.sensitivity_profile — NOT Gaussian noise
 *   - Is guaranteed to have a unique sensitivity profile (5-tuple) via rejection sampling
 *
 * Count distribution uses the largest-remainder method so that the sum of per-archetype
 * counts equals totalBuyers exactly.
 *
 * @param {object} [options]
 * @param {number} [options.totalBuyers=800] - Total number of agents to spawn
 * @param {number} [options.seed=42] - RNG seed for deterministic generation
 * @returns {Array<object>} Array of agent objects, length === totalBuyers
 * @throws {Error} If totalBuyers is not a positive integer or seed is not an integer
 */
export function spawnBuyerAgents({ totalBuyers = 800, seed = 42 } = {}) {
  if (!Number.isInteger(totalBuyers) || totalBuyers <= 0) {
    throw new Error(`[agent-spawner] totalBuyers must be a positive integer, got ${totalBuyers}`);
  }
  if (!Number.isInteger(seed)) {
    throw new Error(`[agent-spawner] seed must be an integer, got ${seed}`);
  }

  // Compute proportional per-archetype counts using largest-remainder method
  const counts = buildCohortCounts(ARCHETYPES, totalBuyers);

  // Name generator: Fisher-Yates shuffled pool of 1200 unique Korean names
  // (30 surnames × 40 given names). Separate seed derivation from trait RNG.
  const nameGen = createKoreanNameGenerator(seed);

  // Trait RNG: derive a well-separated seed so the trait stream is uncorrelated
  // with the name generator's internal stream even when both start from the same seed.
  const traitSeed = Math.imul(seed ^ (seed >>> 16), 0x45d9f3b) >>> 0;
  const rng = mulberry32(traitSeed);

  // Rejection sampling: track every 5-tuple profile seen so far.
  // sensitivity_variation() draws uniformly from [-10%, +10%), yielding discrete
  // values at 0.1 resolution across [1, 5]. With 4 sensitivity fields + pass_threshold
  // there are thousands of unique combinations per archetype, far exceeding the
  // largest cohort (144 agents). The 500-attempt guard prevents infinite loops.
  const profilesSeen = new Set();

  const agents = [];
  let globalIndex = 0;

  for (const { archetype, count } of counts) {
    for (let i = 0; i < count; i++) {
      globalIndex += 1;
      const paddedIndex = String(globalIndex).padStart(4, '0');
      const agent_id = `${archetype.id}_${paddedIndex}`;
      const korean_name = nameGen.next();

      // Rejection-sample until we get a unique sensitivity profile
      let traits;
      let profile;
      let attempts = 0;
      do {
        traits = {
          price_sensitivity: sensitivity_variation(archetype.price_sensitivity, rng),
          trust_sensitivity: sensitivity_variation(archetype.trust_sensitivity, rng),
          promo_affinity: sensitivity_variation(archetype.promo_affinity, rng),
          brand_bias: sensitivity_variation(archetype.brand_bias, rng),
          pass_threshold: varyPassThreshold(archetype.pass_threshold, rng),
        };
        profile = `${traits.price_sensitivity}|${traits.trust_sensitivity}|${traits.promo_affinity}|${traits.brand_bias}|${traits.pass_threshold}`;
        attempts += 1;
        if (attempts > 500) {
          throw new Error(
            `[agent-spawner] Cannot generate unique sensitivity profile for archetype `
            + `"${archetype.id}" after 500 attempts — profile space may be exhausted.`,
          );
        }
      } while (profilesSeen.has(profile));

      profilesSeen.add(profile);

      agents.push({
        agent_id,
        korean_name,
        archetype_id: archetype.id,
        budget_band: archetype.budget_band,
        price_sensitivity: traits.price_sensitivity,
        trust_sensitivity: traits.trust_sensitivity,
        promo_affinity: traits.promo_affinity,
        brand_bias: traits.brand_bias,
        pass_threshold: traits.pass_threshold,
        copy_preference: archetype.copy_preference,
      });
    }
  }

  // ── Post-spawn invariants ────────────────────────────────────────────────

  if (agents.length !== totalBuyers) {
    throw new Error(
      `[agent-spawner] Expected ${totalBuyers} agents but spawned ${agents.length}`,
    );
  }

  if (profilesSeen.size !== totalBuyers) {
    throw new Error(
      `[agent-spawner] Expected ${totalBuyers} unique sensitivity profiles but got ${profilesSeen.size}`,
    );
  }

  return agents;
}
